#! /usr/bin/expect 
#------------------------------------------------
# Author:    vj
# Created:   Mon Sep 24 21:41:30 IST 2012
# File Name: login
# USAGE: 
#       login 
# 
# 
#------------------------------------------------
spawn sudo openvpn --config linux_client.conf
expect "Enter Auth Username:"
send "vijayakrishna.kasula@students.iiit.ac.in\r"
expect "Enter Auth Password:"
send "alpir88A\r"
wait
