#! /usr/bin/perl -wl
#------------------------------------------------
# Author:    vj
# Created:   Tue Nov 20 13:03:26 IST 2012
# File Name: generator
# USAGE: 
#       generator 
# 
# 
#------------------------------------------------
use strict;

my $itr = 100;

my $range = 0x100;
my $minAddr = int rand (0xFFFF_FFFF - $range);
my $maxAddr = $minAddr + $range;

while ($itr--) {
        printf "0x%08X 0x%02X %d %d\n", $minAddr + int rand $range, int rand 0x100, int rand 2, 1 + int rand 10;
}
