#! /usr/bin/perl -wl
#------------------------------------------------
# Author:    vj
# Created:   Fri Nov 30 22:06:09 IST 2012
# File Name: generator
# USAGE: 
#       generator 
# 
# 
#------------------------------------------------
use strict;

my @addr = int rand 0x0000_0000;
$addr[1] = $addr[0] + 0xFFFF_FFFF;

foreach (0 .. 100) {
        printf "0x%08X 0x%02X %d %d\n", $addr[0] + int rand ($addr[1] - $addr[0] + 1), int rand 0x100, int rand 2, int rand 16;
}
