#! /bin/tcsh
#------------------------------------------------
# Author:    kvkrishna
# Created:   Tue Apr 19 19:33:50 IST 2011
# File Name: test
# 
# 
# 
# 
#------------------------------------------------
ls > temp
