#! /bin/tcsh
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri May  6 14:07:29 IST 2011
# File Name: BaseConvert
# 
# 
# 
# 
#------------------------------------------------
bc -l << END
        obase=$argv[2]
        ibase=$argv[1]
        `echo $argv[3*] | tr '[a-z ]' '[A-Z\n]'`
END
