#! /bin/tcsh -f
#------------------------------------------------
# Author:    kasula
# Created:   Thu Jul 21 23:01:48 PDT 2011
# File Name: Comm
# 
# 
# 
# 
#------------------------------------------------
if ($#argv != 3) then
        echo "$0:t : Improper args list..."
        echo "Usage: file1  <minus|and|or> file2"
        exit 8
endif

sort $argv[1] -o $argv[1]
sort $argv[3] -o $argv[3]

switch ($argv[2])
case "minus":
        comm -23 $argv[1] $argv[3]
        breaksw
case "and":
        comm -12 $argv[1] $argv[3]
        breaksw
case "or":
        sort $argv[1] $argv[3]
        breaksw
default:
        echo "Usage: file1  <minus|and|or> file2"
        exit 8
        breaksw
endsw
