#! /bin/tcsh
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Mar 30 12:09:01 IST 2011
# File Name: RandStr
# 
# 
# 
# 
#------------------------------------------------
set VALIDCHARS = (0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z _)
set OpFileName
@ i = $argv[1]
while ($i > 0)
        set INDEX = `RandInt 1 $#VALIDCHARS`
        set OpFileName = "$OpFileName""$VALIDCHARS[$INDEX]"
        @ i = $i - 1
end
echo $OpFileName
