#! /usr/bin/env tcsh
#------------------------------------------------
# Author:    krishna
# Created:   Sun Dec 17 00:33:31 IST 2017
# File Name: run
# USAGE:
#       run
# Description:
# 
#------------------------------------------------
rm -rf profileReport* sim* ucli.key csrc
time vcs -sverilog -full64 -q `cat defines.v ` -simprofile emergence.sv
time ./simv  -simprofile time -simprofile noreport > ! log
# profrpt -q -view time_all -format ALL simprofile_dir
time grep -P '^(\d+,){3}\d+$' log | uniq > ! log.csv
time ./show.py log.csv
