#! /bin/tcsh -f
#------------------------------------------------
# Author:    kasula
# Created:   Tue Sep  6 03:28:08 PDT 2011
# File Name: Account
# USAGE: 
# 
# 
# 
#------------------------------------------------Default Values
set InstallDir = "/remote/us01home15/kasula/.MyAccounts"
set Date = `date +%F`
set Types = ('Pay_IN' 'Pay_OUT' 'Transfers(Self)' 'Transfers(3rd-Party)');
#------------------------------------------------1st Arg...
if ( $#argv ) then
	goto GetARGV1
else
	goto ARGV1
endif
#------------------------------------------------1st Arg Process...
GetARGV1:

        switch ( $argv[1] )
        case "-setup":
                set NewInstallDir = `zenity --entry --title "InstallDir" --text "Enter an Installation Directory.."`
                mkdir -p $NewInstallDir/Books $NewInstallDir/Sources $NewInstallDir/Accounts
                touch $NewInstallDir/.accounts.csv $NewInstallDir/.sources.csv $NewInstallDir/.3rd-party.csv
		touch $NewInstallDir/Books/`date +%Y`_Book.csv $NewInstallDir/Books/`date +%Y%m`_Book.csv
		echo '"Date","Type Of Transaction","Comments","From","To","Amount"'
                sed -i 's#^set InstallDir.*#set InstallDir = "'$NewInstallDir'"#g' $0
                exit 0
                breaksw
	endsw
	shift
endif
#------------------------------------------------Reading Args...
while ( $#argv > 0 )
        set Option = `echo $1 | tr 'A-Z' 'a-z'`
        shift
        switch ($Option)
        case '-date':
                set Date = `date -d $argv[1] +%F`
                shift
                breaksw
        case '-amount':
                @ Amount = $argv[1]
                shift
                breaksw
        case '-type':
                set Type = $Types[$argv[1]]
                shift
                breaksw
        case '-comment':
                set Comment = "$argv[1]"
                shift
                breaksw
        case '-from':
                set From = $argv[1]
                shift
                breaksw
        case '-to':
                set To = $argv[1]
                shift
                breaksw
        case '-h':
                grep -m 1 -A 3 USAGE $0
                exit
                breaksw
        default:
                echo "Invalid Option found...\nTry '-h' to know valid options\n"
                exit
                breaksw
        endsw
end
#------------------------------------------------Validating data...
if ( ! $?Amount  ) @   Amount  = `zenity --entry --title "Amount"  --text "Please enter an AMOUNT..."`
if ( ! $?Comment ) set Comment = `zenity --entry --title "Comment" --text "Please COMMENT on transaction..."`
if ( ! $?Type    ) set Type    = `zenity --list  --title "Types"   --text "Please select one of the TYPES" --column "Types" $Types`
switch ( $Type )
case "$Types[1]":
set From = From
set To = To
#------------------------------------------------Pre Process...
#if (-e -f ~/)
#------------------------------------------------Confirm what is being recorded...
zenity --question --title "Confirm" --text "Date\t\t$Date\nAmount\t$Amount\nType\t\t$Type\nComment\t$Comment\nFrom\t\t$From\nTo\t\t$To" >&! /dev/null
if ( $? ) then
        echo "Cancelled"
else
        echo "Recorded"
endif
