#! /bin/tcsh -f
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Mar 30 13:55:50 IST 2011
# File Name: argvtest
# 
# 
# 
# 
#------------------------------------------------
echo $0
echo $1
echo $2
echo "---\n$3-\n---"
shift 
echo $*
