#! /bin/tcsh -f
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Jun  8 14:33:25 IST 2011
# File Name: CommTester
# 
# 
# 
# 
#------------------------------------------------
date
repeat 200 RandInt 2000 >! f1
date
repeat 200 RandInt 2000 >! f2
date
sort -u f1 -o f1
sort -u f2 -o f2
date
( comm -12 f1 f2 ; echo --- ; comm -13 f1 f2 ; echo --- ; comm -23 f1 f2 ) > ! comm.log
date
( Comm f1 and f2 ; echo --- ; Comm f2 minus f1 ; echo --- ; Comm f1 minus f2 ) > ! Comm.log
date
diff -s Comm.log comm.log
