#! /bin/sh
#------------------------------------------------
# Author:    kvkrishna
# Created:   Mon Apr 25 15:26:59 IST 2011
# File Name: Func
# 
# 
# 
# 
#------------------------------------------------
MyFunc () {
  echo "Hi"
}

MyFunc
