#! /bin/tcsh
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Apr 20 21:11:32 IST 2011
# File Name: SelfEx
# 
# 
# 
# 
#------------------------------------------------
@ a = 145
@ b = $a + 1
replace -s "@ a = $a" "@ a = $b" -- $0
$0
