#! /usr/bin/perl
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri Jun 17 15:06:51 IST 2011
# File Name: spr
# 
# 
# 
# 
#------------------------------------------------
open FH, "<f";
while (<FH>) {
        @Fields = split '|', $_;
        print "$Fields[3]\n";
}
