#! /bin/tcsh
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri May 13 15:54:21 IST 2011
# File Name: switchtest
# 
# 
# 
# 
#------------------------------------------------
while ( $#argv > 0)
        switch ( $argv[1] )
        case "-h":
                echo "In Help"
                breaksw
        endsw
        shift
end
