#! /bin/tcsh -f
# Menu file

#set -vx

set clear	= "tput clear"
set bold	= "tput bold"
set bell	= "tput bel"
set off		= "tput sgr0"

#export clear bold bell off

${bold}
echo "\n\n              WELCOME TO"
echo "            MENU PROGRAM OF"
echo "         THE PHONEBOOK PROJECT \n\n"
${off}

echo "\tPress `${bold}`A`${off}` to add information to the phonebook."
echo "\tPress `${bold}`C`${off}` to change phonebook information."
echo "\tPress `${bold}`D`${off}` to display phonebook information."
echo "\tPress `${bold}`R`${off}` to remove phonebook information."
echo "\tPress `${bold}`Q`${off}` to quit the phonebook."
set choice = $<

${bell}
echo "\tYou have chosen $choice."

#set +vx
