#!/bin/sh
(
echo "10.45 % Finished" ; sleep 1
echo "# Updating mail logs" ; sleep 1
echo "20.45 % Finished" ; sleep 1
echo "# Resetting cron jobs" ; sleep 1
echo "50.3% Finished" ; sleep 1
echo "This line will just be ignored" ; sleep 1
echo "75.23% Finished" ; sleep 1
echo "# Rebooting system" ; sleep 1
echo "100% Done" ; sleep 1
) |
zenity --progress \
  --title="Update System Logs" \
  --text="Scanning mail logs..." \
  --percentage=0

if [ "$?" = -1 ] ; then
        zenity --error \
          --text="Update canceled."
fi
