#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri Aug 19 14:15:25 IST 2011
# File Name: Account
# USAGE: 
# 
# 
# 
#------------------------------------------------
#sub ;
#------------------------------------------------Default Values
chomp ($Date = `date +%F`);
chomp ($File = "~/Accounts/".`date +%Y_%b`);
$Amount = $Type = $Reason = $From = $To = "-";
%TN = (1, 'Spent', 2, 'SelfTransfers', 3, 'ThirdPartyTransfers');
#------------------------------------------------Reading Args...
while ( scalar @ARGV > 0 ) {
        $_ = lc shift ;
        if      ( /^-date$/      ) { $Date   = shift; next; }
        elsif   ( /^-amount$/    ) { $Amount = shift; next; }
        elsif   ( /^-type$/      ) { $Type   = shift; next; }
        elsif   ( /^-reason$/    ) { $Reason = shift; next; }
        elsif   ( /^-from$/      ) { $From   = shift; next; }
        elsif   ( /^-to$/        ) { $To     = shift; next; }
        elsif   ( /^-h$|^-help$/ ) { system "grep -m 1 -A 3 USAGE $0"; exit; }
        else    { die "Invalid Option found...\nTry '-h' or '-help' to know valid options\n"; }
}
#------------------------------------------------Validating data...
chomp ($Date = `date -d $Date +%F`);
if ( $Date   eq ""          ) { die "$Date\n"; }
if ( $Amount eq ""          ) { die "Please specify a valid Amount\n"; }
if ( $Reason eq ""          ) { die "Please specify a Reason\n"; }
if ( $Type !~ /^1$|^2$|^3$/ ) { die "Please specify one of the Type \n\t1 [$TN{1}]\n\t2 [$TN{2}]\n\t3 [$TN{3}]\n"; }
#------------------------------------------------Pre Process...
#if (-e -f ~/)
#------------------------------------------------Print to terminal...
system ("zenity --height=270 --width=270 --list --title \"Recorded...\" --text \"To file : $File...\" --column \"Field\" --column \"Value\" Date $Date Amount $Amount Type $TN{$Type} Reason $Reason From $From To $To");
