#! /usr/bin/perl
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri Apr 15 20:53:15 IST 2011
# File Name: Constants
# 
# 
# 
# 
#------------------------------------------------
use Readonly ;
Readonly::@arr => (1, 2, 3, 4, 5) ;
print "@arr\n" ;
