#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Mon Feb  6 01:00:04 PST 2012
# File Name: Context
# USAGE: 
#       Context 
# 
# 
#------------------------------------------------
sub MrSensitive {
        return wantarray ? (1, 2, 3, 4) : 1;
}
$Scalar = &MrSensitive;
@Vector = &MrSensitive;
printf "$Scalar\n@Vector\n%s %s %s %s\n%s\n  %s\n", &MrSensitive, &MrSensitive;
