#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Thu Apr 14 20:34:27 IST 2011
# File Name: FILE2HASH
# 
# 
# 
# 
#------------------------------------------------

sub FILE2HASH ;
#------------------

$main_hashed_file = FILE2HASH "<$ARGV[0]" ;
while ( ($k, $v) = each %$main_hashed_file ) {
        print "$k => $v\n" ;
}

sub FILE2HASH {
        my %sub_hashed_file = () ;
        open STR_FH, "@_" or die ;
        while (<STR_FH>){
                chomp ;
                my ($key, $val) = split / / ;
                $key =~ s/"//g ;
                $val =~ s/"//g ;
                $sub_hashed_file{$key} = $val ;
        }
        close STR_FH ;
        return (\%sub_hashed_file) ;
}
