#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri Aug 19 15:13:57 IST 2011
# File Name: Date
# USAGE: 
# 
# 
# 
#------------------------------------------------
print time;
