#! /usr/bin/perl -wli
#------------------------------------------------
# Author:    kasula
# Created:   Tue Jul 19 04:36:33 PDT 2011
# File Name: Encrypt
# 
# 
# 
# 
#------------------------------------------------
$key = shift;
while (<>) {
        chomp;
        print $_ ^ substr ($key x (1 + ((length ) / (length $key))), 0, length);
}
