#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Thu Jul 14 12:38:18 IST 2011
# File Name: Fact
# 
# 
# 
# 
#------------------------------------------------
foreach $No ( @ARGV ) {
        $Root = sqrt $No;
        printf "Factors of $No...\n";
        for ($i=1; $i <= $Root; $i++) {
                printf "%8d X %-8d\n", $i, ($No / $i) if (! ($No % $i));
        }
}
