#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Sun Sep 25 23:18:01 PDT 2011
# File Name: getctest
# USAGE: 
# 
# 
# 
#------------------------------------------------
while (1) {
        sysread (STDIN, $KEY, 1);
        print "$KEY\n";
}
