#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Fri May 27 09:54:50 IST 2011
# File Name: GrowingArr
# 
# 
# 
# 
#------------------------------------------------
@Arr = (1,2,3,4,5,6,7,8,9,0);
$i = 0;
foreach (@Arr) {
        $i++;
        push @Arr, $_ if ($i < 10);
        printf "$i \t @Arr\n";
}
