#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Mon Apr 18 10:08:14 IST 2011
# File Name: ModuleTest
# 
# 
# 
# 
#------------------------------------------------
use lib "$ENV{HOME}/Auto/PerlModules" ;
use MyModule ;
use MyTop ;
DISP () ;
@PACK::Arr = (1,2,3,4);
DISP () ;
#print join "\n", @INC ;
print "\n" ;
