#! /usr/bin/perl -w     
#------------------------------------------------
# Author:    kvkrishna
# Created:   Thu Aug 18 10:12:42 IST 2011
# File Name: MultiLinePatMatch
# USAGE: 
# 
# 
# 
#------------------------------------------------
open FH, "<$ARGV[0]";
while (<FH>) {
        if (/1/../9/) {
                print if (/3/../6/);
        }
}
