#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Tue Feb  7 08:33:46 PST 2012
# File Name: PackUp
# USAGE: 
#       PackUp 
# 
# 
#------------------------------------------------
$buf = pack("CCCC", 140, 186, 65, 25);
print "$buf\n";
@Vals = unpack("w*", "ABCD");
printf "%X %X %X %X\n", @Vals;
