#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Mon May 16 16:55:22 IST 2011
# File Name: RandIntAnalyze
# 
# 
# 
# 
#------------------------------------------------
%Stat = () ;
$NO   = 1000 ;
$Cnt  = 999999 ;
$Stat{int rand $NO}++ while ($Cnt--) ;
print "$k\t$v\n" while (($k,$v) = each %Stat) ;
