#! /usr/bin/perl -w
#
@words = (123, 456, 789) ;
print "@words\n" ;
@sdrow = reverse @words ;               # trivial
print "@sdrow\n" ;
$rev   = reverse $words[0] ;            # trivial
print "$rev\n" ;
$rev   = reverse @words ;               # reverse words and chars and join to single var
print "$rev\n" ;
$rev   = @words ;                       # gives count
print "$rev\n" ;
