#! /bin/tcsh -f
#------------------------------------------------
# Author:    kvkrishna
# Created:   Thu Aug  4 10:35:58 IST 2011
# File Name: temp
# USAGE: 
# 
# 
# 
#------------------------------------------------
set COLUMNS=`tput cols`
set LINES=`tput lines`
set line=`expr $LINES / 2`
set column=`expr \( $COLUMNS - 6 \) / 2`
tput sc
tput cup $line $column
tput rev
echo 'Hello, World'
tput sgr0
tput rc
