#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed May 18 21:14:31 IST 2011
# File Name: WRand
# 
# 
# 
# 
#------------------------------------------------
sub wrand {
        my $i = 0;
        my $Tot = 0;
        for ($i=0; $i < @_; $i+=2) {
                $Tot += $_[$i] ;
        }
        my $SUM = 0;
        my $Val = 1 + int rand $Tot ;
        for ($i=0; $i < @_; $i+=2) {
                $SUM += $_[$i] ;
                return $_[$i+1] and last if ( $SUM >= $Val) ;
        }
}
@a = (1,2,3,4);
@b = (5,6);
@c = (1,2,5);
@d = (3);
@WArr = (scalar @a, \@a, scalar @b, \@b, scalar @c, \@c, scalar @d, \@d);
$Res = wrand @WArr ;
print "@$Res\n" ;
#$Trgt = 99999;
#while ($Trgt--){
#        $Val = wrand @ARGV;
#        $OP{$Val}++ ;
#}
#print "$_\t$OP{$_}\n" foreach sort keys %OP ;
