#! /usr/bin/env tcsh
#------------------------------------------------
# Author:    krishna
# Created:   Mon Sep 25 10:56:47 IST 2017
# File Name: addKeyToRemoteHost
# USAGE:
#       addKeyToRemoteHost <Remote Host Name>
# Description:
# 
#------------------------------------------------
if (! -f ~/.ssh/id_rsa.pub) ssh-keygen -t rsa
cat ~/.ssh/id_rsa.pub | ssh $argv[1] 'cat >> .ssh/authorized_keys'
