#! /usr/bin/env tcsh
#------------------------------------------------
# Author:    krishna
# Created:   Sun Sep 24 10:31:57 IST 2017
# File Name: gitSync
# USAGE:
#       gitSync
# Description:
# 
#------------------------------------------------
foreach n ($argv)
  cd $n
  git pull | & grep -v 'Already up-to-date.'
  cd -
end
