#! /bin/csh -f
set echo_style = both
################################# please do not indent this code...
switch ( $1 )
case "-put" :
ftp us01-ftp-int.synopsys.com << EOF_CMDS
  cd /outgoing
  hash
  bin
  put $2
  bye
EOF_CMDS

breaksw

case "-get":
ftp us01-ftp-int.synopsys.com << EOF_CMDS
  cd /incoming
  hash
  bin
  get $2
  bye
EOF_CMDS
breaksw

case "-h":
case "-help":
case "--h":
case "--help":
  echo ""
  echo "MyFTP (1)"
  echo ""
  echo "`tput bold`NAME`tput sgr0`"
  echo "\tMyFTP - small script to send/recieve a single file in current directory"
  echo ""
  echo "`tput bold`SYNOPSIS`tput sgr0`"
  echo "\tMyFTP [-put/-get] filename"
  echo ""
  echo "`tput bold`DESCRIPTION`tput sgr0`"
  echo "\tfile must be in current directory only"
  echo ""
  echo "\t`tput bold`ARG1:`tput sgr0` put/get"
  echo "\t\t-put:\tsend a file"
  echo "\t\t-get:\trecieve a file"
  echo ""
  echo "\t`tput bold`ARG2:`tput sgr0` filename"
  echo ""
breaksw

default:
  echo "MyFTP:\tInvalid argument"
  exit 1
breaksw
endsw
