#! /usr/bin/env perl
#------------------------------------------------
# Author:    krishna
# Created:   Fri May 19 12:35:17 IST 2017
# File Name: nameNumber
# USAGE:
#       nameNumber
# Description:
# 
#------------------------------------------------
use strict;
use warnings;
use List::Util qw(first max maxstr min minstr reduce shuffle sum);

my $data = lc join "", @ARGV;

# Strip non alphabits
$data =~ s#[^a-z]##g;

my $res = sum map {(ord $_) - (ord 'a') + 1} split //, $data;
$res = sum split //, $res while (1 < length $res);
printf "$res\n";
