#! /usr/bin/env python3
'''
Author:    kvkrishna
Created:   Tue Jan 26 13:22:47 IST 2011
File Name: New
Usage:
      New interpreter FileName
Description:
  Creates a new script file with header and few obvious lines of code
'''
import re, os, sys, shutil, textwrap
from datetime import datetime, timezone


def getPythonFooter():
    return textwrap.dedent(
        """\
        import argparse


        def getOpts():
            '''Process the options'''

            parser = argparse.ArgumentParser(
                description='''Add description here'''
            )

            # return validateOpts(parser.parse_args())
            return parser.parse_args()


        def main():
            '''The Main'''

            opts = getOpts()


        if __name__ == '__main__':
            main()

        """
    )


def getCommentType(interpreter):
    '''Return the prefix for comments and seperator to seperator header'''

    # Even for Python, use normal comments in header to allow adhoc indentations

    # For Python, Add footer
    footer = ""
    if re.match("python.*", interpreter, flags=re.I):
        footer = getPythonFooter()

    return ("# ", "------------------------------------------------", footer)


def main():
    assert (len(sys.argv) == 3), "Improper arguments, expecting an interpreter and a FileName"

    interpreter = sys.argv[1]
    filename    = sys.argv[2]

    assert (None != shutil.which(interpreter)), "Could not find interpreter %s" % interpreter
    assert (False == os.path.lexists(filename)), "The path %s already exists" % filename

    prefix, seperator, footer = getCommentType(interpreter)

    with open (filename, "w") as f:
        f.write (
            ("\n%s" % prefix).join ([
                "#! /usr/bin/env %s" % interpreter,
                seperator,
                "Author:    %s" % os.environ['USER'],
                # "Created:   %s" % datetime.now(timezone.utc).astimezone().strftime("%c %Z"),
                "USAGE:",
                "      %s" % os.path.basename(filename),
                "Description:",
                "",
                "",
                seperator
            ]) + "\n"
        )

        f.write(footer)

    os.chmod(filename, 0o700)


if __name__ == '__main__':
    main()
