#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Mar 30 11:21:25 IST 2011
# File Name: RandInt
# 
# 
# 
# 
#------------------------------------------------
if (1 == scalar @ARGV)
{
        printf "%d\n", (int(rand($ARGV[0]))) ;
}
else
{
        printf "%d\n", ($ARGV[0] + int(rand($ARGV[1]-$ARGV[0]+1))) ;
}
