#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Thu Oct 13 23:19:20 PDT 2011
# File Name: rl
# USAGE: 
#       rl 
# 
# 
#------------------------------------------------
use List::Util 'shuffle';
print shuffle (<>);
