#! /usr/bin/perl -wl
#------------------------------------------------
# Author:    kasula
# Created:   Fri Aug  3 04:24:20 PDT 2012
# File Name: transpose
# USAGE: 
#       transpose 
# 
# 
#------------------------------------------------
use strict;
my @rows;
while (<>) {
  chomp; @_ = split /,/;
  for (my $i=0; $i<@_; $i++) { push @{$rows[$i]}, $_[$i] }
}
print join ",", @{$_} foreach ( @rows );
