#! /usr/bin/tcsh
#------------------------------------------------
# Author:    vj
# Created:   Sat Sep 15 07:26:26 IST 2012
# File Name: run
# USAGE: 
#       run 
# 
# 
#------------------------------------------------
set prgm = $argv[1]
../bin/sslittle-na-sstrix-gcc $prgm -o $prgm:r.out -c -g -Wa,-a,-ad > & ! $prgm:r.lst
../bin/sslittle-na-sstrix-objdump --disassemble-all $prgm:r.out > & ! $prgm:r.dump
../simplesim-3.0/sim-bpred -bpred taken $prgm:r.out > & ! $prgm:r.log
