#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Sat Jul  9 07:38:00 PDT 2011
# File Name: Analyze
# 
# 
# 
# 
#------------------------------------------------
#foreach $Trgt (@ARGV) {
        system ("TESTTMP=432");
        print "$ENV{TESTTMP}\n";
#}
#        for ($SubGrps = 1, $SubTrgt = int $Trgt; $SubTrgt > $SubGrps; ) {    
