#! /bin/tcsh -f
#------------------------------------------------
# Author    kasula
# Created   Mon Nov 14 030104 PST 2011
# File Name SyncSVN
# USAGE 
#       SyncSVN 
# 
# 
#------------------------------------------------
svn add ~/Auto/Files/*
svn add ~/Auto/Fun/*
svn add ~/Auto/MyPerl/*
svn add ~/Auto/MyShell/*
svn add ~/Auto/Perl/*
svn add ~/Auto/Shell/*

svn ci -m 'Sync...' ~/Auto
