#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Aug  3 14:51:39 IST 2011
# File Name: ScrSvr1
# USAGE: 
# 
# 
# 
#------------------------------------------------
$Lines = `tput lines` - 1;
$Cols  = `tput cols`  - 1;
system "tput clear";
system "tput civis";
while (1) {
        ($X, $Y) = (int rand $Lines, int rand $Cols) ;
        system "tput cup $X $Y" ;
        printf "%d", int rand 2 ;
        for ($i=0; $i<25; $i++) {
                ($X, $Y) = (int rand $Lines, int rand $Cols) ;
                system "tput cup $X $Y" ;
                printf " ", int rand 128 ;
        }
}
