#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Jun  8 12:52:11 IST 2011
# File Name: Comm
# 
# 
# 
# 
#------------------------------------------------
die "Invalid Arg list"                  if (scalar @ARGV != 3      ) ;
system "grep -wx  -f $ARGV[2] $ARGV[0]" if (lc($ARGV[1]) eq 'and'  ) ;
system "grep -vwx -f $ARGV[2] $ARGV[0]" if (lc($ARGV[1]) eq 'minus') ;
system "sort         $ARGV[2] $ARGV[0]" if (lc($ARGV[1]) eq 'or'   ) ;
