#! /usr/bin/perl -wl
#------------------------------------------------
# Author:    kasula
# Created:   Mon Nov  7 03:12:52 PST 2011
# File Name: csv2html
# USAGE: 
#       csv2html <file.csv>
# 
# 
#------------------------------------------------
print "<table><tbody>";
while ( <> ) {
  chomp;
  next if (/^\s*$/);
  printf "<tr>\n%s\n</tr>\n", join "\n", map { "\<td\> $_ \</td\>" } split /,/;
}
print "</tbody></table>";
