#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Mon Nov  7 03:12:52 PST 2011
# File Name: csv2html
# USAGE: 
#       csv2html <file.csv> <file.html>
# 
# 
#------------------------------------------------
if ( $#ARGV != 1 ){
        die "Usage: perl csv2html <in.csv> <out.html>\n" ;
}
open(IN,"$ARGV[0]") or die "Can’t open $ARGV[0]\n";
chomp($ARGV[1]);
open(H,">$ARGV[1]") || die "Can’t write to $ARGV[1]; check permissions\n";
print H ("\<table border=1 width=50\%\>\n");
while(<IN>){
        chomp($_);
        @fields = split(/\,/,$_);
        print H "  \<tr align=center valign=left\>\n";
        @htmlfields = map("\<td\> $_ \</td\>\n", @fields);
        print H @htmlfields;
        print H ("  \<\/tr\>\n");
}
print H ("</table>\n\n");
close(IN);
close(H);
