#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Thu May 19 12:00:00 IST 2011
# File Name: InstDiss
# 
# 
# 
# 
#------------------------------------------------
$InstrWord = $ARGV[0];
@Fields = unpack ("A5 A3 A2 A6 A1 A3 A6 A6", sprintf "%032b", hex $InstrWord );
printf "\t---------------------------------------\n" ;
#printf "\t%-5s %-3s %-2s %-6s %-1s %-3s %-6s %-6s\n", 'I', '', 'P', 'i', 'F', '', '', '' ;
printf "\t  I       P     i   F\n" ;
printf "\t@Fields\n" ;
printf "\t---------------------------------------\n" ;
printf "\t$Fields[0]bbb$Fields[2]$Fields[3]FBBB\n";
