#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kvkrishna
# Created:   Wed Mar 30 11:21:25 IST 2011
# File Name: RandInt
# 
# 
# 
# 
#------------------------------------------------
if (1 == scalar @ARGV)
{
        $VAL = int(rand($ARGV[0])) ;
}
else
{
        $VAL = $ARGV[0] + int(rand($ARGV[1]-$ARGV[0]+1)) ;
}
print "$VAL\n" ;
