#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Thu Oct 13 23:19:20 PDT 2011
# File Name: rl
# USAGE: 
#       rl 
# 
# 
#------------------------------------------------
open IFH, "$ARGV[0]" or die "Opening $ARGV[0] failed\n";
@Lines = <IFH>;
close IFH;

for ($i = @Lines; --$i; ) {
        $j = int rand ($i+1);
        next if $i == $j;
        @Lines[$i,$j] = @Lines[$j,$i];
}
print @Lines;
