#! /usr/bin/perl -w
#------------------------------------------------
# Author:    kasula
# Created:   Mon Nov 14 02:55:21 PST 2011
# File Name: Tabulate
# USAGE: 
#       Tabulate 
# 
# 
#------------------------------------------------
use GetOpts
